apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      run: {{ .Release.Name }}
  template:
    metadata: 
      labels: 
        run: {{ .Release.Name }}
    spec:
      containers: 
        - name: about-me
          image: kadeksuryam/about-me:{{ .Values.image.tag }}
          ports:
            - containerPort: 80 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
