apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.environment }}
  labels:
    run: {{ .Release.Name }}
spec:
  selector:
    run: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
