---
- name: Update list of available apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: safe
    autoremove: true
    
- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
