---
- name: Set amd64 architecture
  ansible.builtin.set_fact:
    docker_arch: amd64
  when: ansible_architecture == "x86_64"

- name: Uninstall any conflicting packages
  ansible.builtin.apt:
    name: "{{ docker_conflicting_packages }}"
    state: absent

- name: Install required dependencies
  ansible.builtin.apt:
    name: "{{ docker_dependencies }}"
    state: present
  
- name: Create directory for Docker's GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Add Docker's official GPG key
  block:
    - name: Get GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
    
    - name: Update GPG key permissions
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        state: file
        mode: 0444

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update list of available apt packages
  ansible.builtin.apt:
    update_cache: true

- name: Install the Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present

- name: Add Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  
- name: Enable docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ docker_services }}"
